### PR TITLE
v0.16.1

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by samuelcolvin** [comment]
thanks so much.

**Comment by bollwyvl** [comment]
A small number of builds didn't go through:

- https://app.travis-ci.com/github/conda-forge/watchfiles-feedstock/builds/253577518

I guess the builds don't have to work every time on every platform/python, but they need to work at least _once_ for e.g. https://github.com/conda-forge/uvicorn-feedstock/issues/91

**Comment by davidbrochart** [comment]
Thanks for reporting, they now all passed: https://app.travis-ci.com/github/conda-forge/watchfiles-feedstock/builds/253577518.

**Pull request merged**
