### PR TITLE
MNT: rerender

### LINKED ISSUE #17: @conda-forge-admin, please rerender
### Additional comment:

https://github.com/conda-forge/watchfiles-feedstock/pull/10/commits/84b53317126ed62bd32e7cfe17292ccb40e74035 was likely intended to cross-compile `linux-aarch64`/`linux-ppc64le` but used the `providers` instead of `build_platform` entry.
Issuing a rerender to open a PR to fix this.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #17.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #17

### CODE REVIEW

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
Looks like cross-compiling with maturin works for `linux-aarch64` but not `linux-ppc64le`.
Will have to take a closer look into why.

**Comment by samuelcolvin** [comment]
@mbargull do you have any idea how widespread use of `linux-ppc64le` is? E.g. download stats or similar?

**Comment by mbargull** [comment]
> @messense is the maturin expert, maybe he has an idea?
> 
> Might be worth trying build with `linux-ppc64le` on the main repo for pypi, just to see if the problem is just here.

I wouldn't be surprised if the build succeeds for native or emulated runs.
I haven't yet used those since I wanted to see if we can see why it fails (cause might be in maturin, but could also be in our Python builds, etc. pp.)
(I don't really care for PPC64le builds but I'm okay with having them if it "just works" alongside the other builds without much further effort. But debugging this could uncover bugs which might be relevant for other platforms as well.)

> @mbargull do you have any idea how widespread use of `linux-ppc64le` is? E.g. download stats or similar?

There is https://github.com/ContinuumIO/anaconda-package-data :
(This is from the current year; data until August, inclusively.)
```python
>>> import intake
>>> cat = intake.open_catalog('https://raw.githubusercontent.com/ContinuumIO/anaconda-package-data/master/catalog/anaconda_package_data.yaml')
>>> y = cat.anaconda_package_data_by_year(year=2022).to_dask()
>>> y[y.data_source == "conda-forge"].groupby("pkg_platform")["counts"].sum().compute().sort_values()
pkg_platform
linux-32                  0
osx-32                    0
linux-armv6l              0
linux-armv7l            911
linux-s390x          141494
win-32              1066070
linux-ppc64le      12173277
osx-arm64          45915883
linux-aarch64      59332597
osx-64            375839043
win-64            496141504
                 2181862192
linux-64         3533753477
Name: counts, dtype: int64
```
I.e., only about 20 % w.r.t. `linux-aarch64` (whereas you can expect increased usage for ARM builds over the next years).
(Personal opinion: I don't know why we burden maintainers with such a problematic (as in harder to get hardware/CI resources) platform.)

**Comment by samuelcolvin** [comment]
Nice, thanks for that. I assume the empty row is where you have no data for platform?

**Comment by messense** [comment]
The only two failure are ppc64le pypy builds which I never tested 🤣. 

Maybe you can just disable ppc64le pypy for now, I may take a deeper look when I have the time.

**Comment by samuelcolvin** [comment]
To be clear, I'm totally happy with dropping ppc64le completely - and especially with pypy.

@mbargull is that as simple as closing that PR, or do we need to do something else?

**Comment by mbargull** [comment]
> Nice, thanks for that. I assume the empty row is where you have no data for platform?

I'd assume those are the one from the `noarch` subdir (`noarch: python`/`noarch: generic`).

**Comment by mbargull** [comment]
Let's leave this open for a few of days. If I don't get to look into it, I'll just drop those or try the emulated build.

**Comment by mbargull** [comment]
I took a quick look and it's really just updating the sysconfig JSON file. I'll prep a PR for maturin.

**Comment by mbargull** [comment]
> I took a quick look and it's really just updating the sysconfig JSON file. I'll prep a PR for maturin.

See https://github.com/PyO3/maturin/pull/1258 .
Once we have a maturin package built with that change, we can rerun the CI here.
(We can just let this PR sit open until then.)

**Comment by ivergara** [comment]
@mbargull The second issue you linked in your previous message is closed and was part of the [v0.14.0](https://github.com/PyO3/maturin/releases/tag/v0.14.0) release a few days ago. Just letting you know.

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender


> @mbargull The second issue you linked in your previous message is closed and was part of the [v0.14.0](https://github.com/PyO3/maturin/releases/tag/v0.14.0) release a few days ago. Just letting you know n case you were not aware.

Nice, thanks! Then let's give this another go!

**Comment by xhochy** [comment]
All builds are green. Can we merge this or is there still something to address here?

**Pull request merged**
